# Generated by Django 4.0.3 on 2022-06-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_investigation_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('call_type', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('imei', models.BigIntegerField()),
                ('imsi', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('investigation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.investigation')),
            ],
        ),
    ]
